start_date: "2018-04-01"
end_date: "2019-06-30"
months: [5, 6, 7, 8, 9]
hrrr_v1_format: ["00z.hrrra", "06z.hrrra", "12z.hrrra", "18z.hrrra"]
hrrr_format: ["00-05_hrrr", "06-11_hrrr", "12-17_hrrr", "18-23_hrrr"]
hrrr1_server: "https://noaa-oar-arl-hysplit-pds.s3.amazonaws.com/hrrr.v1"
hrrr_server: "https://noaa-oar-arl-hysplit-pds.s3.amazonaws.com/hrrr" 
